name: Update metrics

on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Update infographics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: mthmulders
          template: terminal
          base: header, metadata
          config_timezone: Europe/Amsterdam